services:
  postgres-user:
    image: postgres:17-alpine3.22
    container_name: user_service_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_USER_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_USER_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres-auth:
    image: postgres:17-alpine3.22
    container_name: auth_service_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_AUTH_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_AUTH_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres-order:
    image: postgres:17-alpine3.22
    container_name: order_service_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_ORDER_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - postgres_order_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_ORDER_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  mongodb:
    image: mongo:7.0
    container_name: payment_service_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: [ "CMD-SHELL", "echo 'db.runCommand({ ping: 1 })' | mongosh localhost:27017/test --quiet" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s


  redis:
    image: redis:7.2
    container_name: redis_container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  user-service:
    build:
      context: inno-user-service/.
      dockerfile: UserService/Dockerfile
    container_name: user-service
    restart: unless-stopped
    ports:
      - "8083:8083"
    env_file:
      - .env
    environment:

      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_CACHE_TYPE: redis

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user:5432/${POSTGRES_USER_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: 8083
    depends_on:
      postgres-user:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://localhost:8083/actuator/health | grep '\"status\":\"UP\"' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 50s

  auth-service:
    build:
      context: ./inno-auth-service
      dockerfile: AuthService/Dockerfile
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "8084:8084"
    env_file:
      - .env
    environment:

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/${POSTGRES_AUTH_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: 8084
    depends_on:
      postgres-auth:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://localhost:8084/actuator/health | grep '\"status\":\"UP\"' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 50s

  order-service:
    build:
      context: inno-order-service/.
      dockerfile: OrderService/Dockerfile
    container_name: order-service
    restart: unless-stopped
    ports:
      - "8085:8085"
    env_file:
      - .env
    environment:
      USER_SERVICE_URL: http://user-service:8083
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-order:5432/${POSTGRES_ORDER_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: 8085
    depends_on:
      postgres-order:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://localhost:8085/actuator/health | grep '\"status\":\"UP\"' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 50s

  api-gateway:
    build:
      context: ./inno-api-gateway
      dockerfile: ApiGateway/Dockerfile
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "8086:8086"
    env_file:
      - .env
    environment:
      SERVER_PORT: 8086

      USER_SERVICE_URL: http://user-service:8083
      AUTH_SERVICE_URL: http://auth-service:8084
      ORDER_SERVICE_URL: http://order-service:8085
      PAYMENT_SERVICE_URL: http://order-service:8087

    depends_on:
      user-service:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      order-service:
        condition: service_healthy
      payment-service:
        condition: service_healthy

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - ./kafka-data:/var/lib/kafka/data

  payment-service:
    build:
      context: ./inno-payment-service
      dockerfile: PaymentService/Dockerfile
    container_name: payment-service
    restart: unless-stopped
    ports:
      - "8087:8087"
    env_file:
      - .env
    environment:
      SERVER_PORT: 8087

      SPRING_DATA_MONGODB_URI: ${MONGO_DB_URL}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_CONSUMER_GROUP_ID: payment-service-group

    depends_on:
      kafka:
        condition: service_started
      mongodb:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://localhost:8087/actuator/health | grep '\"status\":\"UP\"' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 50s

volumes:
  postgres_user_data:
  postgres_auth_data:
  postgres_order_data:
  redis_data:
  kafka-data:
  mongodb_data: