spring:
  liquibase:
    driver-class-name: liquibase.ext.mongodb.database.MongoClientDriver
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
  data:
    mongodb:
      uri: ${MONGO_DB_URL}
      database: payment-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    properties:
      spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      spring.json.trusted.packages: "*"
      spring.json.value.default.type: com.innowise.paymentservice.model.dto.OrderEvent
    topics:
      create-order: create_order
      create-payment: create_payment

server:
  port: 8087
random:
  api:
    url: ${RANDOM_API_UPL}



