spring:
  liquibase:
    driver-class-name: liquibase.ext.mongodb.database.MongoClientDriver
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
  data:
    mongodb:
      uri: ${MONGO_DB_URL}
      database: payment-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    properties:
      spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      spring.json.trusted.packages: "*"
      spring.json.value.default.type: com.innowise.paymentservice.model.dto.OrderEvent
    topics:
      create-order: create_order
      create-payment: create_payment

server:
  port: 8087
random:
  api:
    url: ${RANDOM_API_UPL}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  security:
    enabled: false
resilience4j:
  circuitbreaker:
    instances:
      payment-service:
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 2
        minimumNumberOfCalls: 2
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
        permittedNumberOfCallsInHalfOpenState: 3